# Reading, Resizing and displaying image

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import cv2

In [2]:
image= cv2.imread("D:\\picturedataset\\1728.jpeg")
image= cv2.resize(image, (400, 200))
cv2.imshow("1728image", image)

cv2.waitKey(0)
cv2.destroyAllWindows()

# converting GBR 2 RGB

In [3]:
img= cv2.imread("D:\\picturedataset\\anwaar.jpeg")
img= cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
cv2.imshow("anwaar_img", img)

cv2.waitKey(0)
cv2.destroyAllWindows()

# Gray color

In [4]:
image_bgr = cv2.imread("D:\\picturedataset\\khan.jpeg")
image_bgr=cv2.resize(image_bgr,(400,200))
image_gray = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2GRAY)

cv2.imshow("khan", image_gray)
cv2.waitKey(0)
cv2.destroyAllWindows()


# convert into matirx 

In [5]:
import cv2

img=cv2.imread("D:\\picturedataset\\niazi.jpeg")

img_matrix=np.array(img)
print(img_matrix)
#cv2.imshow("img_matrix", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[112  85  41]
  [112  85  41]
  [112  85  41]
  ...
  [118  91  47]
  [118  91  47]
  [118  91  47]]

 [[112  85  41]
  [112  85  41]
  [112  85  41]
  ...
  [118  91  47]
  [118  91  47]
  [118  91  47]]

 [[112  85  41]
  [112  85  41]
  [112  85  41]
  ...
  [118  91  47]
  [118  91  47]
  [118  91  47]]

 ...

 [[ 95  75  40]
  [ 95  75  40]
  [ 95  75  40]
  ...
  [102  76  36]
  [102  76  36]
  [102  76  36]]

 [[ 95  75  40]
  [ 95  75  40]
  [ 95  75  40]
  ...
  [102  76  36]
  [102  76  36]
  [102  76  36]]

 [[ 95  75  40]
  [ 95  75  40]
  [ 95  75  40]
  ...
  [102  76  36]
  [102  76  36]
  [102  76  36]]]


# color chanal

In [6]:
import cv2
import numpy as np

img=cv2.imread("D:\\picturedataset\\niazi.jpeg")

img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

blue_channel, green_channel, red_channel = cv2.split(img_rgb)
zero_channel=np.zeros(img_rgb.shape[0:2],dtype="uint8")

blue_img=cv2.merge([blue_channel, zero_channel, zero_channel])

blue_matrix= np.array(blue_img)

print(blue_matrix)

cv2.imshow('Blue Channel', blue_channel)
cv2.imshow('Red Channel', red_channel)
cv2.imshow('Green Channel', green_channel)

cv2.waitKey(0)
cv2.destroyAllWindows()

[[[41  0  0]
  [41  0  0]
  [41  0  0]
  ...
  [47  0  0]
  [47  0  0]
  [47  0  0]]

 [[41  0  0]
  [41  0  0]
  [41  0  0]
  ...
  [47  0  0]
  [47  0  0]
  [47  0  0]]

 [[41  0  0]
  [41  0  0]
  [41  0  0]
  ...
  [47  0  0]
  [47  0  0]
  [47  0  0]]

 ...

 [[40  0  0]
  [40  0  0]
  [40  0  0]
  ...
  [36  0  0]
  [36  0  0]
  [36  0  0]]

 [[40  0  0]
  [40  0  0]
  [40  0  0]
  ...
  [36  0  0]
  [36  0  0]
  [36  0  0]]

 [[40  0  0]
  [40  0  0]
  [40  0  0]
  ...
  [36  0  0]
  [36  0  0]
  [36  0  0]]]
